
package org.jubaroo.mods.leaderboardtitles.configurator;

import org.jubaroo.mods.leaderboardtitles.Initiator;

import java.util.logging.Logger;

public class Constants {

    public static Logger logger;
    public static boolean debug;
    public static boolean titles;

    // Male Titles
    public static String titleMale900;
    public static String titleMale901;
    public static String titleMale902;
    public static String titleMale903;
    public static String titleMale904;
    public static String titleMale905;
    public static String titleMale906;
    public static String titleMale907;
    public static String titleMale908;
    public static String titleMale909;
    public static String titleMale910;
    public static String titleMale911;
    public static String titleMale912;
    public static String titleMale913;
    public static String titleMale914;
    public static String titleMale915;
    public static String titleMale916;
    public static String titleMale917;
    public static String titleMale918;
    public static String titleMale919;
    public static String titleMale920;
    public static String titleMale921;
    public static String titleMale922;
    public static String titleMale923;
    public static String titleMale924;
    public static String titleMale925;
    public static String titleMale926;
    public static String titleMale927;
    public static String titleMale928;
    public static String titleMale929;
    public static String titleMale930;
    public static String titleMale931;
    public static String titleMale932;
    public static String titleMale933;
    public static String titleMale934;
    public static String titleMale935;
    public static String titleMale936;
    public static String titleMale937;
    public static String titleMale938;
    public static String titleMale939;
    public static String titleMale940;
    public static String titleMale941;
    public static String titleMale942;
    public static String titleMale943;
    public static String titleMale944;
    public static String titleMale945;
    public static String titleMale946;
    public static String titleMale947;
    public static String titleMale948;
    public static String titleMale949;
    public static String titleMale950;
    public static String titleMale951;
    public static String titleMale952;
    public static String titleMale953;
    public static String titleMale954;
    public static String titleMale955;
    public static String titleMale956;
    public static String titleMale957;
    public static String titleMale958;
    public static String titleMale959;
    public static String titleMale960;
    public static String titleMale961;
    public static String titleMale962;
    public static String titleMale963;
    public static String titleMale964;
    public static String titleMale965;
    public static String titleMale966;
    public static String titleMale967;
    public static String titleMale968;
    public static String titleMale969;
    public static String titleMale970;
    public static String titleMale971;
    public static String titleMale972;
    public static String titleMale973;
    public static String titleMale974;
    public static String titleMale975;
    public static String titleMale976;
    public static String titleMale977;
    public static String titleMale978;
    public static String titleMale979;
    public static String titleMale980;
    public static String titleMale981;
    public static String titleMale982;
    public static String titleMale983;
    public static String titleMale984;
    public static String titleMale985;
    public static String titleMale986;
    public static String titleMale987;
    public static String titleMale988;
    public static String titleMale989;
    public static String titleMale990;
    public static String titleMale991;
    public static String titleMale992;
    public static String titleMale993;
    public static String titleMale994;
    public static String titleMale995;
    public static String titleMale996;
    public static String titleMale997;
    public static String titleMale998;
    public static String titleMale999;
    // Female Titles
    public static String titleFemale900;
    public static String titleFemale901;
    public static String titleFemale902;
    public static String titleFemale903;
    public static String titleFemale904;
    public static String titleFemale905;
    public static String titleFemale906;
    public static String titleFemale907;
    public static String titleFemale908;
    public static String titleFemale909;
    public static String titleFemale910;
    public static String titleFemale911;
    public static String titleFemale912;
    public static String titleFemale913;
    public static String titleFemale914;
    public static String titleFemale915;
    public static String titleFemale916;
    public static String titleFemale917;
    public static String titleFemale918;
    public static String titleFemale919;
    public static String titleFemale920;
    public static String titleFemale921;
    public static String titleFemale922;
    public static String titleFemale923;
    public static String titleFemale924;
    public static String titleFemale925;
    public static String titleFemale926;
    public static String titleFemale927;
    public static String titleFemale928;
    public static String titleFemale929;
    public static String titleFemale930;
    public static String titleFemale931;
    public static String titleFemale932;
    public static String titleFemale933;
    public static String titleFemale934;
    public static String titleFemale935;
    public static String titleFemale936;
    public static String titleFemale937;
    public static String titleFemale938;
    public static String titleFemale939;
    public static String titleFemale940;
    public static String titleFemale941;
    public static String titleFemale942;
    public static String titleFemale943;
    public static String titleFemale944;
    public static String titleFemale945;
    public static String titleFemale946;
    public static String titleFemale947;
    public static String titleFemale948;
    public static String titleFemale949;
    public static String titleFemale950;
    public static String titleFemale951;
    public static String titleFemale952;
    public static String titleFemale953;
    public static String titleFemale954;
    public static String titleFemale955;
    public static String titleFemale956;
    public static String titleFemale957;
    public static String titleFemale958;
    public static String titleFemale959;
    public static String titleFemale960;
    public static String titleFemale961;
    public static String titleFemale962;
    public static String titleFemale963;
    public static String titleFemale964;
    public static String titleFemale965;
    public static String titleFemale966;
    public static String titleFemale967;
    public static String titleFemale968;
    public static String titleFemale969;
    public static String titleFemale970;
    public static String titleFemale971;
    public static String titleFemale972;
    public static String titleFemale973;
    public static String titleFemale974;
    public static String titleFemale975;
    public static String titleFemale976;
    public static String titleFemale977;
    public static String titleFemale978;
    public static String titleFemale979;
    public static String titleFemale980;
    public static String titleFemale981;
    public static String titleFemale982;
    public static String titleFemale983;
    public static String titleFemale984;
    public static String titleFemale985;
    public static String titleFemale986;
    public static String titleFemale987;
    public static String titleFemale988;
    public static String titleFemale989;
    public static String titleFemale990;
    public static String titleFemale991;
    public static String titleFemale992;
    public static String titleFemale993;
    public static String titleFemale994;
    public static String titleFemale995;
    public static String titleFemale996;
    public static String titleFemale997;
    public static String titleFemale998;
    public static String titleFemale999;
    // Title ID Names
    public static String titleName900;
    public static String titleName901;
    public static String titleName902;
    public static String titleName903;
    public static String titleName904;
    public static String titleName905;
    public static String titleName906;
    public static String titleName907;
    public static String titleName908;
    public static String titleName909;
    public static String titleName910;
    public static String titleName911;
    public static String titleName912;
    public static String titleName913;
    public static String titleName914;
    public static String titleName915;
    public static String titleName916;
    public static String titleName917;
    public static String titleName918;
    public static String titleName919;
    public static String titleName920;
    public static String titleName921;
    public static String titleName922;
    public static String titleName923;
    public static String titleName924;
    public static String titleName925;
    public static String titleName926;
    public static String titleName927;
    public static String titleName928;
    public static String titleName929;
    public static String titleName930;
    public static String titleName931;
    public static String titleName932;
    public static String titleName933;
    public static String titleName934;
    public static String titleName935;
    public static String titleName936;
    public static String titleName937;
    public static String titleName938;
    public static String titleName939;
    public static String titleName940;
    public static String titleName941;
    public static String titleName942;
    public static String titleName943;
    public static String titleName944;
    public static String titleName945;
    public static String titleName946;
    public static String titleName947;
    public static String titleName948;
    public static String titleName949;
    public static String titleName950;
    public static String titleName951;
    public static String titleName952;
    public static String titleName953;
    public static String titleName954;
    public static String titleName955;
    public static String titleName956;
    public static String titleName957;
    public static String titleName958;
    public static String titleName959;
    public static String titleName960;
    public static String titleName961;
    public static String titleName962;
    public static String titleName963;
    public static String titleName964;
    public static String titleName965;
    public static String titleName966;
    public static String titleName967;
    public static String titleName968;
    public static String titleName969;
    public static String titleName970;
    public static String titleName971;
    public static String titleName972;
    public static String titleName973;
    public static String titleName974;
    public static String titleName975;
    public static String titleName976;
    public static String titleName977;
    public static String titleName978;
    public static String titleName979;
    public static String titleName980;
    public static String titleName981;
    public static String titleName982;
    public static String titleName983;
    public static String titleName984;
    public static String titleName985;
    public static String titleName986;
    public static String titleName987;
    public static String titleName988;
    public static String titleName989;
    public static String titleName990;
    public static String titleName991;
    public static String titleName992;
    public static String titleName993;
    public static String titleName994;
    public static String titleName995;
    public static String titleName996;
    public static String titleName997;
    public static String titleName998;
    public static String titleName999;

    static {
        logger = Logger.getLogger(Initiator.class.getName());
        debug = false;
        titles = false;

        // Title Names
        titleName900 = "UNUSED_900";
        titleName901 = "UNUSED_901";
        titleName902 = "UNUSED_902";
        titleName903 = "UNUSED_903";
        titleName904 = "UNUSED_904";
        titleName905 = "UNUSED_905";
        titleName906 = "UNUSED_906";
        titleName907 = "UNUSED_907";
        titleName908 = "UNUSED_908";
        titleName909 = "UNUSED_909";
        titleName910 = "UNUSED_910";
        titleName911 = "UNUSED_911";
        titleName912 = "UNUSED_912";
        titleName913 = "UNUSED_913";
        titleName914 = "UNUSED_914";
        titleName915 = "UNUSED_915";
        titleName916 = "UNUSED_916";
        titleName917 = "UNUSED_917";
        titleName918 = "UNUSED_918";
        titleName919 = "UNUSED_919";
        titleName920 = "UNUSED_920";
        titleName921 = "UNUSED_921";
        titleName922 = "UNUSED_922";
        titleName923 = "UNUSED_923";
        titleName924 = "UNUSED_924";
        titleName925 = "UNUSED_925";
        titleName926 = "UNUSED_926";
        titleName927 = "UNUSED_927";
        titleName928 = "UNUSED_928";
        titleName929 = "UNUSED_929";
        titleName930 = "UNUSED_930";
        titleName931 = "UNUSED_931";
        titleName932 = "UNUSED_932";
        titleName933 = "UNUSED_933";
        titleName934 = "UNUSED_934";
        titleName935 = "UNUSED_935";
        titleName936 = "UNUSED_936";
        titleName937 = "UNUSED_937";
        titleName938 = "UNUSED_938";
        titleName939 = "UNUSED_939";
        titleName940 = "UNUSED_940";
        titleName941 = "UNUSED_941";
        titleName942 = "UNUSED_942";
        titleName943 = "UNUSED_943";
        titleName944 = "UNUSED_944";
        titleName945 = "UNUSED_945";
        titleName946 = "UNUSED_946";
        titleName947 = "UNUSED_947";
        titleName948 = "UNUSED_948";
        titleName949 = "UNUSED_949";
        titleName950 = "UNUSED_950";
        titleName951 = "UNUSED_951";
        titleName952 = "UNUSED_952";
        titleName953 = "UNUSED_953";
        titleName954 = "UNUSED_954";
        titleName955 = "UNUSED_955";
        titleName956 = "UNUSED_956";
        titleName957 = "UNUSED_957";
        titleName958 = "UNUSED_958";
        titleName959 = "UNUSED_959";
        titleName960 = "UNUSED_960";
        titleName961 = "UNUSED_961";
        titleName962 = "UNUSED_962";
        titleName963 = "UNUSED_963";
        titleName964 = "UNUSED_964";
        titleName965 = "UNUSED_965";
        titleName966 = "UNUSED_966";
        titleName967 = "UNUSED_967";
        titleName968 = "UNUSED_968";
        titleName969 = "UNUSED_969";
        titleName970 = "UNUSED_970";
        titleName971 = "UNUSED_971";
        titleName972 = "UNUSED_972";
        titleName973 = "UNUSED_973";
        titleName974 = "UNUSED_974";
        titleName975 = "UNUSED_975";
        titleName976 = "UNUSED_976";
        titleName977 = "UNUSED_977";
        titleName978 = "UNUSED_978";
        titleName979 = "UNUSED_979";
        titleName980 = "UNUSED_980";
        titleName981 = "UNUSED_981";
        titleName982 = "UNUSED_982";
        titleName983 = "UNUSED_983";
        titleName984 = "UNUSED_984";
        titleName985 = "UNUSED_985";
        titleName986 = "UNUSED_986";
        titleName987 = "UNUSED_987";
        titleName988 = "UNUSED_988";
        titleName989 = "UNUSED_989";
        titleName990 = "UNUSED_990";
        titleName991 = "UNUSED_991";
        titleName992 = "UNUSED_992";
        titleName993 = "UNUSED_993";
        titleName994 = "UNUSED_994";
        titleName995 = "UNUSED_995";
        titleName996 = "UNUSED_996";
        titleName997 = "UNUSED_997";
        titleName998 = "UNUSED_998";
        titleName999 = "UNUSED_999";

        // Male Titles
        titleMale900 = "UNUSED";
        titleMale901 = "UNUSED";
        titleMale902 = "UNUSED";
        titleMale903 = "UNUSED";
        titleMale904 = "UNUSED";
        titleMale905 = "UNUSED";
        titleMale906 = "UNUSED";
        titleMale907 = "UNUSED";
        titleMale908 = "UNUSED";
        titleMale909 = "UNUSED";
        titleMale910 = "UNUSED";
        titleMale911 = "UNUSED";
        titleMale912 = "UNUSED";
        titleMale913 = "UNUSED";
        titleMale914 = "UNUSED";
        titleMale915 = "UNUSED";
        titleMale916 = "UNUSED";
        titleMale917 = "UNUSED";
        titleMale918 = "UNUSED";
        titleMale919 = "UNUSED";
        titleMale920 = "UNUSED";
        titleMale921 = "UNUSED";
        titleMale922 = "UNUSED";
        titleMale923 = "UNUSED";
        titleMale924 = "UNUSED";
        titleMale925 = "UNUSED";
        titleMale926 = "UNUSED";
        titleMale927 = "UNUSED";
        titleMale928 = "UNUSED";
        titleMale929 = "UNUSED";
        titleMale930 = "UNUSED";
        titleMale931 = "UNUSED";
        titleMale932 = "UNUSED";
        titleMale933 = "UNUSED";
        titleMale934 = "UNUSED";
        titleMale935 = "UNUSED";
        titleMale936 = "UNUSED";
        titleMale937 = "UNUSED";
        titleMale938 = "UNUSED";
        titleMale939 = "UNUSED";
        titleMale940 = "UNUSED";
        titleMale941 = "UNUSED";
        titleMale942 = "UNUSED";
        titleMale943 = "UNUSED";
        titleMale944 = "UNUSED";
        titleMale945 = "UNUSED";
        titleMale946 = "UNUSED";
        titleMale947 = "UNUSED";
        titleMale948 = "UNUSED";
        titleMale949 = "UNUSED";
        titleMale950 = "UNUSED";
        titleMale951 = "UNUSED";
        titleMale952 = "UNUSED";
        titleMale953 = "UNUSED";
        titleMale954 = "UNUSED";
        titleMale955 = "UNUSED";
        titleMale956 = "UNUSED";
        titleMale957 = "UNUSED";
        titleMale958 = "UNUSED";
        titleMale959 = "UNUSED";
        titleMale960 = "UNUSED";
        titleMale961 = "UNUSED";
        titleMale962 = "UNUSED";
        titleMale963 = "UNUSED";
        titleMale964 = "UNUSED";
        titleMale965 = "UNUSED";
        titleMale966 = "UNUSED";
        titleMale967 = "UNUSED";
        titleMale968 = "UNUSED";
        titleMale969 = "UNUSED";
        titleMale970 = "UNUSED";
        titleMale971 = "UNUSED";
        titleMale972 = "UNUSED";
        titleMale973 = "UNUSED";
        titleMale974 = "UNUSED";
        titleMale975 = "UNUSED";
        titleMale976 = "UNUSED";
        titleMale977 = "UNUSED";
        titleMale978 = "UNUSED";
        titleMale979 = "UNUSED";
        titleMale980 = "UNUSED";
        titleMale981 = "UNUSED";
        titleMale982 = "UNUSED";
        titleMale983 = "UNUSED";
        titleMale984 = "UNUSED";
        titleMale985 = "UNUSED";
        titleMale986 = "UNUSED";
        titleMale987 = "UNUSED";
        titleMale988 = "UNUSED";
        titleMale989 = "UNUSED";
        titleMale990 = "UNUSED";
        titleMale991 = "UNUSED";
        titleMale992 = "UNUSED";
        titleMale993 = "UNUSED";
        titleMale994 = "UNUSED";
        titleMale995 = "UNUSED";
        titleMale996 = "UNUSED";
        titleMale997 = "UNUSED";
        titleMale998 = "UNUSED";
        titleMale999 = "UNUSED";

        // Female Titles
        titleFemale900 = "UNUSED";
        titleFemale901 = "UNUSED";
        titleFemale902 = "UNUSED";
        titleFemale903 = "UNUSED";
        titleFemale904 = "UNUSED";
        titleFemale905 = "UNUSED";
        titleFemale906 = "UNUSED";
        titleFemale907 = "UNUSED";
        titleFemale908 = "UNUSED";
        titleFemale909 = "UNUSED";
        titleFemale910 = "UNUSED";
        titleFemale911 = "UNUSED";
        titleFemale912 = "UNUSED";
        titleFemale913 = "UNUSED";
        titleFemale914 = "UNUSED";
        titleFemale915 = "UNUSED";
        titleFemale916 = "UNUSED";
        titleFemale917 = "UNUSED";
        titleFemale918 = "UNUSED";
        titleFemale919 = "UNUSED";
        titleFemale920 = "UNUSED";
        titleFemale921 = "UNUSED";
        titleFemale922 = "UNUSED";
        titleFemale923 = "UNUSED";
        titleFemale924 = "UNUSED";
        titleFemale925 = "UNUSED";
        titleFemale926 = "UNUSED";
        titleFemale927 = "UNUSED";
        titleFemale928 = "UNUSED";
        titleFemale929 = "UNUSED";
        titleFemale930 = "UNUSED";
        titleFemale931 = "UNUSED";
        titleFemale932 = "UNUSED";
        titleFemale933 = "UNUSED";
        titleFemale934 = "UNUSED";
        titleFemale935 = "UNUSED";
        titleFemale936 = "UNUSED";
        titleFemale937 = "UNUSED";
        titleFemale938 = "UNUSED";
        titleFemale939 = "UNUSED";
        titleFemale940 = "UNUSED";
        titleFemale941 = "UNUSED";
        titleFemale942 = "UNUSED";
        titleFemale943 = "UNUSED";
        titleFemale944 = "UNUSED";
        titleFemale945 = "UNUSED";
        titleFemale946 = "UNUSED";
        titleFemale947 = "UNUSED";
        titleFemale948 = "UNUSED";
        titleFemale949 = "UNUSED";
        titleFemale950 = "UNUSED";
        titleFemale951 = "UNUSED";
        titleFemale952 = "UNUSED";
        titleFemale953 = "UNUSED";
        titleFemale954 = "UNUSED";
        titleFemale955 = "UNUSED";
        titleFemale956 = "UNUSED";
        titleFemale957 = "UNUSED";
        titleFemale958 = "UNUSED";
        titleFemale959 = "UNUSED";
        titleFemale960 = "UNUSED";
        titleFemale961 = "UNUSED";
        titleFemale962 = "UNUSED";
        titleFemale963 = "UNUSED";
        titleFemale964 = "UNUSED";
        titleFemale965 = "UNUSED";
        titleFemale966 = "UNUSED";
        titleFemale967 = "UNUSED";
        titleFemale968 = "UNUSED";
        titleFemale969 = "UNUSED";
        titleFemale970 = "UNUSED";
        titleFemale971 = "UNUSED";
        titleFemale972 = "UNUSED";
        titleFemale973 = "UNUSED";
        titleFemale974 = "UNUSED";
        titleFemale975 = "UNUSED";
        titleFemale976 = "UNUSED";
        titleFemale977 = "UNUSED";
        titleFemale978 = "UNUSED";
        titleFemale979 = "UNUSED";
        titleFemale980 = "UNUSED";
        titleFemale981 = "UNUSED";
        titleFemale982 = "UNUSED";
        titleFemale983 = "UNUSED";
        titleFemale984 = "UNUSED";
        titleFemale985 = "UNUSED";
        titleFemale986 = "UNUSED";
        titleFemale987 = "UNUSED";
        titleFemale988 = "UNUSED";
        titleFemale989 = "UNUSED";
        titleFemale990 = "UNUSED";
        titleFemale991 = "UNUSED";
        titleFemale992 = "UNUSED";
        titleFemale993 = "UNUSED";
        titleFemale994 = "UNUSED";
        titleFemale995 = "UNUSED";
        titleFemale996 = "UNUSED";
        titleFemale997 = "UNUSED";
        titleFemale998 = "UNUSED";
        titleFemale999 = "UNUSED";
    }

}
